apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: component1
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: component1
  namespace: kargo-configs
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/awiesner4/kargo-demo.git
      includePaths:
      - compiled/components/component1
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: component1-configs-dev-use1-poc-5
  namespace: kargo-configs
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/awiesner4/kargo-demo.git
      includePaths:
      - compiled/clusters/dev-use1-poc-5/component1/values.yml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: component1-configs-dev-use1-app-3
  namespace: kargo-configs
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/awiesner4/kargo-demo.git
      includePaths:
      - compiled/clusters/dev-use1-app-3/component1/values.yml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: component1-configs-dev-use1-app-4
  namespace: kargo-configs
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/awiesner4/kargo-demo.git
      includePaths:
      - compiled/clusters/dev-use1-app-4/component1/values.yml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: component1-configs-dev-use1-app-5
  namespace: kargo-configs
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/awiesner4/kargo-demo.git
      includePaths:
      - compiled/clusters/dev-use1-app-5/component1/values.yml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: component1-configs-dev
  namespace: kargo-configs
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/awiesner4/kargo-demo.git
      includePaths:
      - compiled/clusters/dev/component1/values.yml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: demo-promo-process
  namespace: kargo-kapitan
spec:
  vars:
  - name: gitopsRepo
    value: https://github.com/awiesner4/kargo-demo
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitopsRepo }}
      checkout:
      - branch: main
        path: ./src
      - branch: stage/${{ ctx.stage }}
        create: true
        path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: copy
    config:
      inPath: ./src/compiled/clusters/${{ ctx.stage }}/component1
      outPath: ./src/compiled/components/component1
  - uses: kustomize-build
    config:
      path: ./src/compiled/components/component1
      outPath: ./out/clusters/${{ ctx.stage }}/component1
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: "Updating component1 for ${{ ctx.meta.message }}"
  - uses: git-push
    config:
      path: ./out
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-use1-poc-5
  namespace: kargo-configs
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: component1-configs-dev-use1-poc-5
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-configs
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev-use1-poc-5
  - origin:
      kind: Warehouse
      name: component1-configs-dev
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-use1-app-3
  namespace: kargo-configs
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev-use1-poc-5
  - origin:
      kind: Warehouse
      name: component1-configs-dev-use1-app-3
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-use1-app-4
  namespace: kargo-configs
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev-use1-poc-5
  - origin:
      kind: Warehouse
      name: component1-configs-dev-use1-app-4
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process