apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/namespace.yml
- resources/project.yml
- resources/project_config.yml
- resources/warehouses.yml
- resources/stages_base.yml
- resources/stages_config.yml
- resources/promotion_tasks.yml

generators:
  - keychain-secret-generator.yaml
