apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
  - includeCRDs: true
    name: hello-world
    releaseName: hello-world
    valuesFile: values.yml
    version: 0.1.0
helmGlobals:
  chartHome: ./src/charts
kind: Kustomization
