apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
  - includeCRDs: true
    name: hello-world
    repo: https://helm.github.io/examples
    releaseName: hello-world
    valuesFile: values.yml
    version: 0.1.0
helmGlobals:
  chartHome: ../../../charts
kind: Kustomization

resources:
  - resources/configmap-component1.yml
