apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: component1-dev-use1-app-4
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/awiesner4/kargo-demo.git
    targetRevision: stage/dev-use1-app-4
    path: clusters/dev-use1-app-4/component1
  destination:
    server: https://kubernetes.default.svc
    namespace: component1-dev-use1-app-4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
