apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: multi-warehouse-single-stage
  namespace: multi-warehouse-single-stage
spec:
  promotionPolicies:
  - stageSelector:
      name: dev-use1-poc-5
    autoPromotionEnabled: true