---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-use1-poc-5
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: component1-configs-dev-use1-poc-5
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev-use1-poc-5
  - origin:
      kind: Warehouse
      name: component1-configs-dev
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-use1-app-3
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev-use1-poc-5
  - origin:
      kind: Warehouse
      name: component1-configs-dev-use1-app-3
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-use1-app-4
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev-use1-poc-5
  - origin:
      kind: Warehouse
      name: component1-configs-dev-use1-app-4
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-use1-app-5
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev-use1-poc-5
  - origin:
      kind: Warehouse
      name: component1-configs-dev-use1-app-5
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-use1-mgt-1
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev-use1-poc-5
  - origin:
      kind: Warehouse
      name: component1-configs-dev-use1-mgt-1
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev
  - origin:
      kind: Warehouse
      name: component1-configs-staging
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stg-use1-app-3
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev
  - origin:
      kind: Warehouse
      name: component1-configs-stg-use1-app-3
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stg-use1-app-4
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev
  - origin:
      kind: Warehouse
      name: component1-configs-stg-use1-app-4
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stg-use1-app-5
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev
  - origin:
      kind: Warehouse
      name: component1-configs-stg-use1-app-5
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stg-use1-mgt-1
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - dev-use1-mgt-1
  - origin:
      kind: Warehouse
      name: component1-configs-stg-use1-mgt-1
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - staging
  - origin:
      kind: Warehouse
      name: component1-configs-prod
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prd-use1-app-3
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - staging
  - origin:
      kind: Warehouse
      name: component1-configs-prd-use1-app-3
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prd-use1-app-4
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - staging
  - origin:
      kind: Warehouse
      name: component1-configs-prd-use1-app-4
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prd-use1-app-5
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - staging
  - origin:
      kind: Warehouse
      name: component1-configs-prd-use1-app-5
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prd-use1-mgt-1
  namespace: multi-warehouse-single-stage
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: component1
    sources:
      stages:
      - stg-use1-mgt-1
  - origin:
      kind: Warehouse
      name: component1-configs-prd-use1-mgt-1
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
