apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
  - includeCRDs: true
    name: keda
    namespace: keda
    releaseName: keda
    repo: https://kedacore.github.io/charts/
    valuesFile: values.yml
    version: 2.17.0
kind: Kustomization
resources:
  - resources/namespace.yml
