prometheus:
  metricServer:
    enabled: true
  operator:
    enabled: true
  webhooks:
    enabled: true

priorityClassName: system-cluster-critical

operator:
  replicaCount: 2

metricsServer:
  replicaCount: 3

webhooks:
  replicaCount: 3

crds:
  install: true
  additionalAnnotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true"

# topologySpreadConstraints:
#   # -- [Pod Topology Constraints] of KEDA operator pod
#   operator:
#     - maxSkew: 1
#       topologyKey: "topology.kubernetes.io/zone"
#       whenUnsatisfiable: DoNotSchedule
#       nodeTaintsPolicy: Honor
#       minDomains: 2
#       labelSelector:
#         matchLabels:
#           app: keda-operator
#   # -- [Pod Topology Constraints] of KEDA metrics apiserver pod
#   metricsServer:
#     - maxSkew: 1
#       topologyKey: "topology.kubernetes.io/zone"
#       whenUnsatisfiable: DoNotSchedule
#       nodeTaintsPolicy: Honor
#       minDomains: 2
#       labelSelector:
#         matchLabels:
#           app: keda-operator-metrics-apiserver
#   # -- [Pod Topology Constraints] of KEDA admission webhooks pod
#   webhooks:
#     - maxSkew: 1
#       topologyKey: "topology.kubernetes.io/zone"
#       whenUnsatisfiable: DoNotSchedule
#       nodeTaintsPolicy: Honor
#       minDomains: 2
#       labelSelector:
#         matchLabels:
#           app: keda-admission-webhooks
    

podDisruptionBudget:
  # -- Capability to configure [Pod Disruption Budget]
  operator:
     minAvailable: 1

  # -- Capability to configure [Pod Disruption Budget]
  metricServer:
     minAvailable: 1

  # -- Capability to configure [Pod Disruption Budget]
  webhooks:
     minAvailable: 1

podAnnotations:
  # -- Pod annotations for KEDA operator
  keda:
    ad.datadoghq.com/keda-operator.checks: |
      {
        "keda": {
          "init_config": {},
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:8080/metrics"
            }
          ]
        }
      }  
  # -- Pod annotations for KEDA Metrics Adapter
  metricsAdapter:
    ad.datadoghq.com/keda-operator-metrics-apiserver.checks: |
      {
        "keda": {
          "init_config": {},
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:8080/metrics"
            }
          ]
        }
      }  
  # -- Pod annotations for KEDA Admission webhooks
  webhooks: 
    ad.datadoghq.com/keda-admission-webhooks.checks: |
      {
        "keda": {
          "init_config": {},
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:8080/metrics"
            }
          ]
        }
      }  