apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: component1-stg-use1-mgt-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/awiesner4/kargo-demo.git
    targetRevision: stage/stg-use1-mgt-1
    path: clusters/stg-use1-mgt-1/component1
  destination:
    server: https://kubernetes.default.svc
    namespace: component1-stg-use1-mgt-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
