
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kargo.akuity.io/project: "true"
  name: component1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-repo-creds
  namespace: component1
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: ${GITOPS_REPO_URL}
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PAT}